export const footerSeed = {
  tagline: "India's trusted labour law consultancy specializing in HR compliance, statutory filings, payroll, and staffing solutions across 15+ states.",
  whatsappUrl:  'https://wa.me/919876543210',
  instagramUrl: 'https://instagram.com/maruconsultancy',
  linkedinUrl:  'https://linkedin.com/company/maruconsultancy',
  facebookUrl:  'https://facebook.com/maruconsultancy',
  twitterUrl:   'https://twitter.com/maruconsultancy',
  socialLinks: [
    { platform: 'whatsapp', href: 'https://wa.me/919876543210', enabled: true },
    { platform: 'instagram', href: 'https://instagram.com/maruconsultancy', enabled: true },
    { platform: 'linkedin', href: 'https://linkedin.com/company/maruconsultancy', enabled: true },
    { platform: 'facebook', href: 'https://facebook.com/maruconsultancy', enabled: true },
    { platform: 'twitter', href: 'https://twitter.com/maruconsultancy', enabled: true },
  ],
  socialLinksConfigured: true,
  address:      '614, Mulund - Goregaon Link Rd, Nahur West, Industrial Area, Bhandup West, Mumbai, Maharashtra 400080',
  phone1:       '+91 98765 43210',
  phone1Href:   'tel:+919876543210',
  phone2:       '022 4567 8900',
  phone2Href:   'tel:02245678900',
  email:        'contact@labourcodes.in',
  newsletterText: 'Subscribe for critical compliance alerts and regulatory updates.',
  mapEmbedUrl: 'https://www.google.com/maps?q=614%2C%20Mulund%20-%20Goregaon%20Link%20Rd%2C%20Nahur%20West%2C%20Industrial%20Area%2C%20Bhandup%20West%2C%20Mumbai%2C%20Maharashtra%20400080&output=embed',
  copyrightName: 'Maru Consultancy Services Pvt. Ltd.',
  devByText: 'Airavata Technologies',
  devByUrl:  'https://www.airavatatechnologies.com/',
  bottomLinks: [
    { label: 'Privacy Policy', href: '#' },
    { label: 'Terms of Service', href: '#' },
    { label: 'Sitemap', href: '#' },
  ],
};
