export const knowledgeCentrePageSeed = {
  singleton: 'knowledge-centre',
  heroEyebrow:  'Compliance Knowledge That Helps You Act',
  heroHeading:  'MCS Knowledge Centre',
  heroSubtext:  "A practical resource for employers, HR professionals, payroll teams and management — staying current with India's evolving labour and compliance framework.",
  heroBgType:   'color',
  heroVideoUrl: '',
  heroImageUrl: '',
  introText: 'The MCS Knowledge Centre functions as a practical resource for employers, HR professionals, payroll teams and management. Explore regulatory updates, compliance guides, minimum wage notifications and expert analysis across India\'s Labour Code framework.',
  faqTitle:   'Frequently Asked Questions',
  faqSubtext: "Common questions from employers and HR professionals about India's Labour Codes and MCS services.",
  faqs: [
    {
      question: "What are India's four Labour Codes?",
      answer: "They are the Code on Wages, 2019; Industrial Relations Code, 2020; Code on Social Security, 2020; and Occupational Safety, Health and Working Conditions Code, 2020.",
    },
    {
      question: "Does every organisation need to review its salary structure?",
      answer: "Employers should assess existing remuneration structures against the applicable definition of wages and related requirements. The impact depends on the organisation's existing salary components and workforce arrangements.",
    },
    {
      question: "Can the Labour Codes affect PF, gratuity and other employment costs?",
      answer: "Potentially. Changes in the wage base and employment framework may affect statutory benefits and costs depending on the facts and applicable provisions.",
    },
    {
      question: "Should appointment letters and HR policies be reviewed?",
      answer: "Yes. Employers should assess whether existing employment documentation, policies and internal processes remain aligned with the applicable framework.",
    },
    {
      question: "Are principal employers and contractors affected?",
      answer: "Yes. Organisations using contract labour should review contractor governance, licensing/registration requirements, wage and social-security compliance, and applicable restrictions concerning core activities.",
    },
    {
      question: "Can MCS conduct a Labour Codes readiness review?",
      answer: "Yes. MCS can review wage structures, payroll, social security, employment documentation, contractors, policies and related compliance processes and provide an implementation roadmap.",
    },
    {
      question: "Does MCS support inspections and statutory notices?",
      answer: "Yes. MCS assists with document review, preparation of submissions, corrective compliance and representation support in applicable labour, EPFO and ESIC matters.",
    },
    {
      question: "Does MCS provide ongoing compliance support?",
      answer: "Yes. Depending on the engagement, MCS can support periodic statutory compliance, registers and records, filings, contractor monitoring, audits and management reporting.",
    },
  ],
};

export const knowledgeArticlesSeed = [
  {
    category:  'labour-codes',
    title:     'Understanding the Definition of Wages under the Labour Codes',
    slug:      'definition-of-wages-labour-codes',
    excerpt:   'The Code on Wages, 2019 introduces a unified definition of wages that affects salary structuring, statutory deductions and employment costs across India.',
    date:      'July 2026',
    readTime:  '8 min read',
    author:    'MCS Team',
    featured:  true,
    order:     1,
    sections:  [
      {
        heading: 'Overview',
        body: 'The Code on Wages, 2019 consolidates four earlier wage-related statutes and introduces a harmonised definition of wages applicable across all covered establishments. Understanding this definition is the starting point for any Labour Codes compliance review.',
      },
      {
        heading: 'What is included in wages?',
        body: 'Wages include basic pay, dearness allowance and retaining allowance. The Code specifies components that are excluded from the definition — provided they are paid in accordance with the applicable conditions.',
      },
      {
        heading: 'The 50% Rule',
        body: 'The Code provides that the excluded components in the aggregate should not exceed fifty percent of the total remuneration. Where they do, the excess is treated as remuneration included in wages. This has direct implications for PF contribution bases, gratuity calculations and other statutory obligations.',
      },
    ],
    keyTakeaways: [
      'A unified definition of wages applies across all four Labour Codes.',
      'Excluded allowances must not in aggregate exceed 50% of total remuneration.',
      'Excess amounts are treated as wages, affecting statutory computation.',
      'Employers should map existing salary structures against the new definition.',
    ],
  },
  {
    category:  'labour-codes',
    title:     '50% Wage Rule: What Employers Need to Review',
    slug:      '50-percent-wage-rule-employer-review',
    excerpt:   'If excluded allowances exceed 50% of total remuneration, the surplus is treated as wages — affecting PF, gratuity and other statutory costs.',
    date:      'July 2026',
    readTime:  '6 min read',
    author:    'MCS Team',
    featured:  true,
    order:     2,
    sections:  [],
    keyTakeaways: [
      'Audit total CTC to identify the ratio of excluded allowances to total pay.',
      'Calculate the impact on PF contribution bases and gratuity.',
      'Restructure salary components where necessary before the Codes are notified.',
      'Engage payroll and HR teams early to manage the implementation.',
    ],
  },
  {
    category:  'labour-codes',
    title:     'Impact of the Labour Codes on Gratuity',
    slug:      'impact-of-labour-codes-on-gratuity',
    excerpt:   'The Social Security Code, 2020 modifies gratuity eligibility and computation, with potential cost implications for employers.',
    date:      'July 2026',
    readTime:  '5 min read',
    author:    'MCS Team',
    featured:  false,
    order:     3,
    sections:  [],
    keyTakeaways: [],
  },
  {
    category:  'compliance-guides',
    title:     'Fixed-Term Employment: Employer Compliance Guide',
    slug:      'fixed-term-employment-compliance-guide',
    excerpt:   'Fixed-term employment under the Industrial Relations Code, 2020 — eligibility, statutory benefits and employer obligations.',
    date:      'July 2026',
    readTime:  '7 min read',
    author:    'MCS Team',
    featured:  false,
    order:     1,
    sections:  [],
    keyTakeaways: [],
  },
  {
    category:  'compliance-guides',
    title:     'Contract Labour and Core Activities under the OSH & WC Framework',
    slug:      'contract-labour-core-activities-osh',
    excerpt:   'The OSH Code introduces restrictions on the deployment of contract labour in core activities. This guide explains the framework and its practical implications.',
    date:      'July 2026',
    readTime:  '9 min read',
    author:    'MCS Team',
    featured:  false,
    order:     2,
    sections:  [],
    keyTakeaways: [],
  },
  {
    category:  'compliance-guides',
    title:     'Principal Employer Compliance: A Practical Checklist',
    slug:      'principal-employer-compliance-checklist',
    excerpt:   'Principal employers bear significant obligations under the Labour Codes. This checklist covers contractor governance, registration and ongoing compliance.',
    date:      'July 2026',
    readTime:  '6 min read',
    author:    'MCS Team',
    featured:  false,
    order:     3,
    sections:  [],
    keyTakeaways: [],
  },
  {
    category:  'downloads',
    title:     'Labour Codes Readiness Checklist for Employers',
    slug:      'labour-codes-readiness-checklist',
    excerpt:   'A comprehensive employer checklist covering wages, social security, industrial relations and occupational safety under the four Labour Codes.',
    date:      'July 2026',
    author:    'MCS Team',
    featured:  true,
    order:     1,
    fileFormat: 'PDF',
    fileSize:   '2.1 MB',
    fileUrl:    '',
    sections:  [],
    keyTakeaways: [],
  },
  {
    category:  'downloads',
    title:     'How to Prepare for an EPFO or ESIC Inspection',
    slug:      'prepare-for-epfo-esic-inspection',
    excerpt:   'A practical guide to document readiness, common inspection points and responses to notices from EPFO and ESIC authorities.',
    date:      'July 2026',
    author:    'MCS Team',
    featured:  false,
    order:     2,
    fileFormat: 'PDF',
    fileSize:   '1.8 MB',
    fileUrl:    '',
    sections:  [],
    keyTakeaways: [],
  },
];
