export const labourCodesSeed = [
  {
    slug: 'code-on-wages',
    codeNumber: '01',
    title: 'Code on Wages, 2019',
    subtitle: 'MCS assists employers in evaluating the implications of the Code on Wages on compensation structures, payroll and statutory benefits.',
    intro: 'The Code on Wages, 2019 consolidates four wage-related statutes into a single framework, expanding the definition of wages and introducing uniform rules on minimum wages, payment of wages, bonus and equal remuneration.',
    body: `MCS helps employers understand how the new definition of wages affects their payroll structure, CTC components and statutory benefit computations. We assist in identifying which remuneration elements fall within or outside the defined wage, conducting the 50% exclusion-threshold analysis, and restructuring pay to maintain compliance without adversely affecting take-home or cost to company.\n\nOur advisory covers minimum wage applicability, floor wage notifications, overtime calculations under the new rules, and the revised framework for statutory bonus. We also support employers in reviewing and aligning payment-of-wages processes, permissible deductions, and employment documentation to reflect the Code's requirements.`,
    coveringAreas: [
      'Definition and computation of wages',
      'Review of inclusions and exclusions in remuneration',
      '50% exclusion-threshold analysis',
      'Minimum wages and applicable wage requirements',
      'Payment of wages and permissible deductions',
      'Overtime implications',
      'Statutory bonus',
      'Equal remuneration principles',
      'Salary and CTC restructuring',
      'Payroll compliance review',
      'Employment documentation alignment',
    ],
    ctaLabel: 'Request a Wage Structure Review',
    order: 0,
  },
  {
    slug: 'code-on-social-security',
    codeNumber: '02',
    title: 'Code on Social Security, 2020',
    subtitle: 'MCS supports employers in assessing and managing social-security obligations under the consolidated framework.',
    intro: `The Code on Social Security, 2020 consolidates nine social-security laws — covering provident fund, ESI, gratuity, maternity, and employees' compensation — into a single statute, extending coverage to new categories of workers and introducing a unified social-security framework.`,
    body: `MCS advises employers on the impact of the Code on their existing social-security programmes and contribution structures. We assist in reviewing EPF and ESI applicability thresholds, understanding the revised gratuity provisions for fixed-term employees, and assessing entitlements under the maternity and employees' compensation chapters.\n\nWe support establishments in evaluating coverage obligations for gig and platform workers, building and construction workers, and unorganised-sector employees. Our team assists with compliance assessments, benefit programme reviews, and the records, processes and documentation required under the consolidated framework.`,
    coveringAreas: [
      "Employees' Provident Fund",
      "Employees' State Insurance",
      'Gratuity',
      'Maternity benefits',
      "Employees' compensation",
      'Fixed-term employee implications',
      'Social-security coverage and contribution reviews',
      'Building and construction worker-related social-security requirements',
      'Employee benefit compliance assessments',
      'Relevant records, processes and documentation',
    ],
    ctaLabel: 'Request a Social Security Review',
    order: 1,
  },
  {
    slug: 'industrial-relations-code',
    codeNumber: '03',
    title: 'Industrial Relations Code, 2020',
    subtitle: 'MCS provides strategic and operational advisory on industrial relations and employment matters.',
    intro: 'The Industrial Relations Code, 2020 consolidates three Central labour laws — the Industrial Disputes Act, the Trade Unions Act and the Industrial Employment (Standing Orders) Act — into a single statute, revising thresholds, introducing fixed-term employment and establishing new negotiating council structures.',
    body: `MCS supports employers in developing and reviewing industrial relations strategy under the revised framework. We assist in drafting and certifying standing orders, managing worker classification issues, and handling fixed-term employment arrangements in accordance with the Code's requirements.\n\nOur advisory covers trade-union recognition, negotiating-union and negotiating-council mechanisms, grievance redressal frameworks, and disciplinary proceedings and domestic enquiry procedures. We also advise on lay-off, retrenchment and closure requirements under the revised thresholds, industrial dispute conciliation, and Reskilling Fund obligations. For establishments undergoing restructuring, we support workforce planning and provide guidance on associated legal and documentation requirements.`,
    coveringAreas: [
      'Industrial relations strategy',
      'Standing Orders',
      'Worker classification',
      'Fixed-term employment',
      'Trade-union matters',
      'Grievance redressal mechanisms',
      'Disciplinary proceedings and domestic enquiries',
      'Lay-off, retrenchment and closure',
      'Industrial disputes and conciliation',
      'Negotiating unions and negotiating councils',
      'Reskilling Fund requirements',
      'Workforce restructuring',
    ],
    ctaLabel: 'Request an IR Advisory',
    order: 2,
  },
  {
    slug: 'osh-working-conditions-code',
    codeNumber: '04',
    title: 'OSH & Working Conditions Code, 2020',
    subtitle: 'MCS assists establishments, principal employers and contractors with compliance requirements relating to occupational safety, health and working conditions.',
    intro: 'The Occupational Safety, Health and Working Conditions Code, 2020 consolidates thirteen Central labour laws into a single framework covering factory and establishment safety, contract labour, inter-state migrant workers, working conditions and employment documentation.',
    body: `MCS advises establishments, principal employers and contractors on their obligations under the OSH Code. We assist with establishment registration and licensing, identify applicable provisions based on workforce size and industry, and help implement compliance programmes across safety, health and working-condition requirements.\n\nOur advisory covers contract labour compliance for principal employers and contractors, core and non-core activity assessments, inter-state migrant worker obligations, and working-hours, leave and welfare provisions. We support establishments in meeting health and safety requirements, issuing appointment letters and employment documentation, and maintaining statutory registers, records and notices. We also provide contractor governance frameworks to help principal employers manage supply-chain compliance effectively.`,
    coveringAreas: [
      'Establishment registration and applicable licensing',
      'Contract labour compliance',
      'Principal employer obligations',
      'Core and non-core activity assessment',
      'Inter-State migrant worker requirements',
      'Working hours, leave and welfare provisions',
      'Health and safety requirements',
      'Appointment letters and employment documentation',
      'Statutory registers, records and notices',
      'Contractor governance and compliance monitoring',
    ],
    ctaLabel: 'Request an OSH Compliance Review',
    order: 3,
  },
];
